### ISSUE TITLE
Issues with ES 2.2.2

### ISSUE THREAD

**Issue by phutchins** [Storj/statusify#3]
Having issues when testing against ES 2.2.2

```
2016-05-10T16:47:43.918Z - debug: Saved report in mongo
2016-05-10T16:47:43.919Z - debug: Found elasticsearch instance for model: elasticsearch
2016-05-10T16:47:43.919Z - debug: Creating in ElasticSearch... _bsontype=ObjectID, id=W2¯41¾±*é
2016-05-10T16:47:43.920Z - debug: ElasticSearch: starting request {"method":"POST","path":"/data-api/report/573210af34319dbeb12ae920","body":{"__v":0,"requestID":"fbaa7b8a-34c0-47b9-810a-901fe8d652f1","timestamp":"2016-05-10T16:47:43.651Z","payment":"jlk3j4k2j34lkjk2l3k4j23gh423lk4","signature":"HyPLB7btKfMU8J7ME9MZ6ouLyU4lf0uXxlRrgLFfY6oXZgUrobn2m0pjUfaNERvaP1FwCBfleSkFjow3vrtMFvo=","_id":"573210af34319dbeb12ae920","contact":{"protocol":"superawesomeprotol","nodeID":"ebb11857d8e7c33dce1d2b1a5fb23ec172ad562a","address":"127.0.0.1","port":1234},"bandwidth":{"upload":10.5,"download":100.8},"storage":{"free":1000,"used":100}},"query":{"op_type":"create"}}
2016-05-10T16:47:44.195Z - debug: ElasticSearch: Request complete
2016-05-10T16:47:44.197Z - warn: [fbaa7b8a-34c0-47b9-810a-901fe8d652f1] method: report.put error: [remote_transport_exception] [Chamber][127.0.0.1:9300][indices:data/write/index[p]] Error: [remote_transport_exception] [Chamber][127.0.0.1:9300][indices:data/write/index[p]]
    at respond (/Users/philip/github/data-api/node_modules/elasticsearch/src/lib/transport.js:289:15)
    at checkRespForFailure (/Users/philip/github/data-api/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/Users/philip/github/data-api/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/Users/philip/github/data-api/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)"
2016-05-10T16:47:44.200Z - info: [fbaa7b8a-34c0-47b9-810a-901fe8d652f1] method: report.put durationMs=390
```

**Comment by niahmiah** [comment]
This issue belongs on data-api, not here.
